### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by mattcony** [OttoWinter/esphomeyaml#83] opened 2018-07-15 01:20 UTC
Using Hass.io easyhomeyaml add-on. Any ideas for this error, trying to upload to an nodemcu-esp32s board with the basic .bin file to my device.

Program failed with code 1

Error loading shared library libstdc++.so.6: No such file or directory (needed by /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++)
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_memory_used: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _Znwj: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_newchunk: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: obstack_free: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _ZdlPvj: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _Znaj: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_begin: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _ZdaPvj: symbol not found

**Comment by OttoWinter** [comment] 2018-07-28 16:01
Duplicate of #19 - Basically right now building firmwares for ESP32s using RPis is not possible.

**Comment by OttoWinter** [comment] 2018-09-27 16:27
Closing as duplicate...

**Closed by OttoWinter** 2018-09-27 16:27 UTC
