### ISSUE TITLE
New integration request: RC522 NFC/RFID controller ($1!)

### ISSUE THREAD

**Issue by rradar** [OttoWinter/esphomeyaml#256] opened 2018-12-04 11:13 UTC
**What new integration would you wish to have?**
RC522 (or MFRC-522) NFC/RFID controller which is THE el cheapo version for nfc/rfid! Often comes shipped with tags (chip and card) to start the fun!
![image](https://user-images.githubusercontent.com/34582688/49437980-48f9a500-f7bd-11e8-8b47-37a6bd9981b2.png)
US $1.30 / set with free shipping :frowning: (Proof link: https://www.aliexpress.com/store/product/1pcs-MFRC-522-RC522-RFID-RF-IC-card-sensor-module-to-send-S50-Fudan-card-keychain/130245_32908997913.html) 

**If possible, provide a link to an existing library for the integration:**
- https://github.com/VBranimir/MQTT_RFID_esp8266
- https://github.com/esprfid/esp-rfid

**Is your feature request related to a problem? Please describe.**
I have this controller and want to switch over to use it with esphomeyaml!

**Additional context**
Maybe the logic itself is already supported thru the PN532 Component? https://esphomelib.com/esphomeyaml/components/pn532.html

**Comment by OttoWinter** [comment] 2018-12-05 06:52
Duplicate of https://github.com/OttoWinter/esphomelib/issues/153

@brandond I believe it also supports ISO 18092 and the other protocols - at least the APIs for it exist.

**Closed by OttoWinter** 2018-12-05 06:52 UTC
