### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by joeyboey** [OttoWinter/esphomeyaml#116] opened 2018-09-16 01:41 UTC
The Hass.io addon fails to install on the 64bit Version of Hass.io because the manifest ist missing. The edge Version also fails to install because some dependencies cannot be installed.

**Comment by OttoWinter** [comment] 2018-09-20 09:21
Duplicate of https://github.com/OttoWinter/esphomeyaml/issues/81, I don't really have a fix for that currently

**Closed by OttoWinter** 2018-09-20 09:21 UTC
