### ISSUE TITLE
Error compiling yaml with ssl_fingerprints

### ISSUE THREAD

**Issue by vlad2005** [OttoWinter/esphomeyaml#5642] opened 2023-10-31 21:32 UTC
### Discussed in https://github.com/esphome/esphome/discussions/5638

<div type='discussions-op-text'>

<sup>Originally posted by **vlad2005** October 31, 2023</sup>
Hi!
I try to use mqtt broker with ssl fingerprint on esp8266, but i got an error when i try to compile.

```
In file included from .piolibdeps\sonerie\AsyncMqttClient-esphome\src/AsyncMqttClient.hpp:23,
                 from .piolibdeps\sonerie\AsyncMqttClient-esphome\src/AsyncMqttClient.h:4,
                 from src\esphome\components\mqtt\mqtt_backend_esp8266.h:6,
                 from src\esphome\components\mqtt\mqtt_client.h:15,
                 from src\esphome\components\mqtt\custom_mqtt_device.h:7,
                 from src\esphome\components\mqtt\custom_mqtt_device.cpp:1:
.piolibdeps\sonerie\ESPAsyncTCP-esphome\src/tcp_axtls.h:44:10: fatal error: include/ssl.h: No such file or directory
   44 | #include "include/ssl.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs\sonerie\src\esphome\components\mqtt\custom_mqtt_device.cpp.o] Error 1
In file included from .piolibdeps\sonerie\AsyncMqttClient-esphome\src/AsyncMqttClient.hpp:23,
                 from .piolibdeps\sonerie\AsyncMqttClient-esphome\src/AsyncMqttClient.h:4,
                 from src\esphome\components\mqtt\mqtt_backend_esp8266.h:6,
                 from src\esphome\components\mqtt\mqtt_client.h:15,
                 from src\esphome\components\mqtt\mqtt_client.cpp:1:
.piolibdeps\sonerie\ESPAsyncTCP-esphome\src/tcp_axtls.h:44:10: fatal error: include/ssl.h: No such file or directory
   44 | #include "include/ssl.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs\sonerie\src\esphome\components\mqtt\mqtt_client.cpp.o] Error 1
In file included from .piolibdeps\sonerie\AsyncMqttClient-esphome\src/AsyncMqttClient.hpp:23,
                 from .piolibdeps\sonerie\AsyncMqttClient-esphome\src/AsyncMqttClient.h:4,
                 from src\esphome\components\mqtt\mqtt_backend_esp8266.h:6,
                 from src\esphome\components\mqtt\mqtt_client.h:15,
                 from src\esphome\components\mqtt\mqtt_component.h:11,
                 from src\esphome\components\mqtt\mqtt_component.cpp:1:
.piolibdeps\sonerie\ESPAsyncTCP-esphome\src/tcp_axtls.h:44:10: fatal error: include/ssl.h: No such file or directory
   44 | #include "include/ssl.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
In file included from .piolibdeps\sonerie\AsyncMqttClient-esphome\src/AsyncMqttClient.hpp:23,
                 from .piolibdeps\sonerie\AsyncMqttClient-esphome\src/AsyncMqttClient.h:4,
                 from src\esphome\components\mqtt\mqtt_backend_esp8266.h:6,
                 from src\esphome\components\mqtt\mqtt_client.h:15,
                 from src\esphome\components\mqtt\mqtt_component.h:11,
                 from src\esphome\components\mqtt\mqtt_cover.h:4,
                 from src\esphome\components\mqtt\mqtt_cover.cpp:1:
.piolibdeps\sonerie\ESPAsyncTCP-esphome\src/tcp_axtls.h:44:10: fatal error: include/ssl.h: No such file or directory
   44 | #include "include/ssl.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs\sonerie\src\esphome\components\mqtt\mqtt_component.cpp.o] Error 1
*** [.pioenvs\sonerie\src\esphome\components\mqtt\mqtt_cover.cpp.o] Error 1
In file included from .piolibdeps\sonerie\AsyncMqttClient-esphome\src/AsyncMqttClient.hpp:23,
                 from .piolibdeps\sonerie\AsyncMqttClient-esphome\src/AsyncMqttClient.h:4,
                 from src\esphome\components\mqtt\mqtt_backend_esp8266.h:6,
                 from src\esphome\components\mqtt\mqtt_client.h:15,
                 from src\esphome\components\mqtt\mqtt_component.h:11,
                 from src\esphome\components\mqtt\mqtt_light.h:8,
                 from src\esphome\components\mqtt\mqtt_light.cpp:1:
.piolibdeps\sonerie\ESPAsyncTCP-esphome\src/tcp_axtls.h:44:10: fatal error: include/ssl.h: No such file or directory
   44 | #include "include/ssl.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs\sonerie\src\esphome\components\mqtt\mqtt_light.cpp.o] Error 1
============================================== [FAILED] Took 1.76 seconds ==============================================
```

it seems that the file ssl.h is not found</div>

**Comment by ssieb** [comment] 2023-10-31 22:06
Duplicate of https://github.com/esphome/issues/issues/2660

**Closed as not planned by ssieb** 2023-10-31 22:06 UTC
